# Generated by Django 6.0.3 on 2026-03-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libr', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL for the book cover'),
        ),
    ]
